import React, { useState } from 'react';
import { Dataset, AnalysisResult } from '../types/dataset';
import {
  FileText,
  Printer,
  Download,
  Copy,
  Check,
  CheckCircle2,
  Sparkles,
  ShieldCheck,
  AlertTriangle,
  Table as TableIcon,
} from 'lucide-react';
import { formatNumber } from '../utils/dataEngine';

interface ReportsPageProps {
  dataset: Dataset;
  analysisResults: AnalysisResult[];
}

export type ReportType =
  | 'executive'
  | 'detailed'
  | 'quality'
  | 'anomalies'
  | 'full';

export const ReportsPage: React.FC<ReportsPageProps> = ({
  dataset,
  analysisResults,
}) => {
  const [selectedReportType, setSelectedReportType] = useState<ReportType>('executive');
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  const { quality, anomalies, records, columns, inferredSchema } = dataset;
  const primaryMeasure = Object.keys(inferredSchema).find(
    (c) => inferredSchema[c].role === 'measure'
  );

  const reportOptions: { id: ReportType; label: string; desc: string }[] = [
    { id: 'executive', label: 'Executive Summary', desc: 'High-level business overview and key KPI highlights' },
    { id: 'detailed', label: 'Detailed Analysis', desc: 'Full question breakdown and verified statistical calculations' },
    { id: 'quality', label: 'Data Quality Report', desc: 'Hygiene audit, null counts, and column health scores' },
    { id: 'anomalies', label: 'Anomaly Report', desc: 'Statistical outlier detection log with IQR and Z-scores' },
    { id: 'full', label: 'Full Dossier', desc: 'Comprehensive end-to-end intelligence synthesis' },
  ];

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    if (!records || records.length === 0) return;
    const header = columns.join(',');
    const rows = records.map((r) =>
      columns.map((c) => JSON.stringify(r[c] ?? '')).join(',')
    );
    const csvContent = 'data:text/csv;charset=utf-8,' + [header, ...rows].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `${dataset.fileName.replace(/\.[^/.]+$/, '')}_export.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleCopyMarkdown = () => {
    const md = `# Executive BI Intelligence Report: ${dataset.fileName}
Date: ${new Date().toLocaleDateString()}
Total Records: ${records.length}
Columns: ${columns.length}
Data Quality Score: ${quality.score}/100
Flagged Anomalies: ${anomalies.length}

## Executive Findings:
${analysisResults.map((r, i) => `### ${i + 1}. ${r.question}\n- **Answer**: ${r.answerSummary}\n- **Metric**: ${r.highlightValue || 'N/A'}\n- **Formula**: \`${r.technicalFormula || 'Calculated'}\``).join('\n\n')}

Generated by AI Data Analyst.`;

    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  return (
    <div className="flex-1 overflow-y-auto p-4 sm:p-8 max-w-6xl mx-auto w-full space-y-8 animate-in fade-in duration-200">
      {/* 1. Page Header & Actions */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-6 border-b border-white/[0.08]">
        <div>
          <div className="flex items-center gap-2 text-xs font-semibold text-[#8B5CF6] uppercase tracking-wider">
            <FileText className="w-4 h-4" />
            <span>Reporting Engine</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-[#F5F7FB] mt-1 tracking-tight">
            Generate Reports
          </h1>
          <p className="text-xs sm:text-sm text-[#9CA7BA] mt-1">
            Exportable business summaries and compliance audits for {dataset.fileName}
          </p>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleCopyMarkdown}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-[#151B28] hover:bg-[#1E2638] text-xs font-semibold text-[#F5F7FB] border border-white/[0.08] transition-colors"
          >
            {copiedMarkdown ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedMarkdown ? 'Copied' : 'Copy Markdown'}</span>
          </button>

          <button
            onClick={handleExportCSV}
            className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-[#151B28] hover:bg-[#1E2638] text-xs font-semibold text-[#F5F7FB] border border-white/[0.08] transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-[#4F8CFF]" />
            <span>Export CSV</span>
          </button>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-r from-[#4F8CFF] to-[#8B5CF6] text-white text-xs font-bold hover:opacity-95 shadow-md shadow-blue-500/25 transition-opacity"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / PDF</span>
          </button>
        </div>
      </div>

      {/* 2. Report Type Selector Chips */}
      <div className="grid grid-cols-1 sm:grid-cols-3 lg:grid-cols-5 gap-3">
        {reportOptions.map((opt) => (
          <button
            key={opt.id}
            onClick={() => setSelectedReportType(opt.id)}
            className={`p-3.5 rounded-2xl text-left border transition-all flex flex-col justify-between ${
              selectedReportType === opt.id
                ? 'bg-[#151B28] border-[#4F8CFF] shadow-sm ring-1 ring-[#4F8CFF]/30'
                : 'bg-[#101522] border-white/[0.06] hover:border-white/[0.15]'
            }`}
          >
            <span className={`text-xs font-bold ${
              selectedReportType === opt.id ? 'text-[#4F8CFF]' : 'text-[#F5F7FB]'
            }`}>
              {opt.label}
            </span>
            <span className="text-[10px] text-[#687386] mt-1 line-clamp-2">
              {opt.desc}
            </span>
          </button>
        ))}
      </div>

      {/* 3. Live Printable Report Document Preview */}
      <div className="rounded-3xl bg-[#151B28] border border-white/[0.08] shadow-2xl p-8 sm:p-10 space-y-8 text-[#F5F7FB]">
        {/* Document Header */}
        <div className="border-b border-white/[0.08] pb-6 flex flex-col sm:flex-row sm:items-baseline justify-between gap-4">
          <div>
            <span className="text-[11px] font-mono uppercase font-bold tracking-widest text-[#4F8CFF]">
              Executive Business Intelligence Dossier
            </span>
            <h2 className="text-2xl font-black text-[#F5F7FB] mt-1 tracking-tight">
              {dataset.fileName}
            </h2>
            <p className="text-xs text-[#9CA7BA] mt-1">
              Synthesized by AI Data Analyst · {new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' })}
            </p>
          </div>

          <div className="flex items-center gap-3">
            <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 text-xs font-mono font-bold">
              <CheckCircle2 className="w-3.5 h-3.5" />
              <span>Audit Passed: {quality.score}/100</span>
            </span>
          </div>
        </div>

        {/* Section: KPI Summary Grid */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-[#9CA7BA] mb-3">
            1. Core Dataset Health & Volume
          </h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
            <div className="p-4 rounded-xl bg-[#101522] border border-white/[0.06]">
              <div className="text-[10px] uppercase font-bold text-[#687386]">Total Records</div>
              <div className="text-xl font-black font-mono text-[#F5F7FB] mt-1">
                {records.length.toLocaleString()}
              </div>
            </div>
            <div className="p-4 rounded-xl bg-[#101522] border border-white/[0.06]">
              <div className="text-[10px] uppercase font-bold text-[#687386]">Analyzed Columns</div>
              <div className="text-xl font-black font-mono text-[#4F8CFF] mt-1">
                {columns.length}
              </div>
            </div>
            <div className="p-4 rounded-xl bg-[#101522] border border-white/[0.06]">
              <div className="text-[10px] uppercase font-bold text-[#687386]">Quality Score</div>
              <div className="text-xl font-black font-mono text-emerald-400 mt-1">
                {quality.score}%
              </div>
            </div>
            <div className="p-4 rounded-xl bg-[#101522] border border-white/[0.06]">
              <div className="text-[10px] uppercase font-bold text-[#687386]">Potential Anomalies</div>
              <div className="text-xl font-black font-mono text-amber-400 mt-1">
                {anomalies.length}
              </div>
            </div>
          </div>
        </div>

        {/* Section: Verified Analysis Findings */}
        {(selectedReportType === 'executive' || selectedReportType === 'detailed' || selectedReportType === 'full') && (
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#9CA7BA] mb-3 flex items-center justify-between">
              <span>2. Verified Natural Language Findings ({analysisResults.length})</span>
              <span className="text-[10px] font-mono text-[#687386]">Direct from records</span>
            </h3>

            {analysisResults.length === 0 ? (
              <div className="p-6 rounded-2xl bg-[#101522] border border-white/[0.06] text-xs text-[#9CA7BA]">
                No questions asked yet. Navigate to AI Analyst to ask questions and populate findings.
              </div>
            ) : (
              <div className="space-y-3">
                {analysisResults.map((r, i) => (
                  <div
                    key={r.id}
                    className="p-5 rounded-2xl bg-[#101522] border border-white/[0.06] space-y-2"
                  >
                    <div className="flex items-center justify-between text-xs font-bold text-[#F5F7FB]">
                      <span className="flex items-center gap-2">
                        <span className="text-[#4F8CFF] font-mono">{i + 1}.</span>
                        <span>{r.question}</span>
                      </span>
                      {r.highlightValue && (
                        <span className="font-mono text-emerald-400 text-sm font-extrabold">
                          {r.highlightValue}
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-slate-300 leading-relaxed">
                      {r.answerSummary}
                    </p>
                    {r.technicalFormula && (
                      <div className="pt-2 text-[10px] font-mono text-[#687386] flex items-center gap-1.5">
                        <span className="text-[#4F8CFF]">Formula:</span>
                        <code>{r.technicalFormula}</code>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        )}

        {/* Section: Data Quality Audit Summary */}
        {(selectedReportType === 'quality' || selectedReportType === 'full') && (
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#9CA7BA] mb-3">
              3. Data Hygiene & Quality Audit
            </h3>
            <div className="p-5 rounded-2xl bg-[#101522] border border-white/[0.06] space-y-3 text-xs">
              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
                <div>Missing Cells: <span className="font-mono font-bold text-white">{quality.missingValuesCount}</span></div>
                <div>Duplicate Rows: <span className="font-mono font-bold text-white">{quality.duplicateRowsCount}</span></div>
                <div>Outlier Records: <span className="font-mono font-bold text-white">{quality.outlierCount}</span></div>
              </div>
              <p className="text-[#9CA7BA] leading-relaxed pt-2 border-t border-white/[0.04]">
                Dataset passed automated hygiene verification. Aggregations safely account for null cells and non-numeric characters.
              </p>
            </div>
          </div>
        )}

        {/* Section: Anomaly Register */}
        {(selectedReportType === 'anomalies' || selectedReportType === 'full') && anomalies.length > 0 && (
          <div>
            <h3 className="text-xs font-bold uppercase tracking-wider text-[#9CA7BA] mb-3">
              4. Statistical Anomaly Register ({anomalies.length} Flagged Points)
            </h3>
            <div className="overflow-x-auto border border-white/[0.06] rounded-2xl bg-[#101522]">
              <table className="w-full text-left text-xs text-[#9CA7BA]">
                <thead className="bg-[#151B28] text-[10px] uppercase font-bold text-[#F5F7FB]">
                  <tr>
                    <th className="px-3.5 py-2 font-mono">Row #</th>
                    <th className="px-3.5 py-2">Column</th>
                    <th className="px-3.5 py-2">Value</th>
                    <th className="px-3.5 py-2">Deviation</th>
                    <th className="px-3.5 py-2">Reason</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.04]">
                  {anomalies.slice(0, 10).map((a) => (
                    <tr key={a.id}>
                      <td className="px-3.5 py-2 font-mono text-white">#{a.rowNumber}</td>
                      <td className="px-3.5 py-2 font-mono text-[#4F8CFF] font-semibold">{a.columnName}</td>
                      <td className="px-3.5 py-2 font-mono text-amber-300 font-bold">{formatNumber(Number(a.value))}</td>
                      <td className="px-3.5 py-2 font-mono">{a.zScore ? `z=${a.zScore}` : `${a.deviationMultiplier}x`}</td>
                      <td className="px-3.5 py-2 text-slate-300">{a.reason}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}

        {/* Document Footer */}
        <div className="pt-6 border-t border-white/[0.08] flex items-center justify-between text-[11px] text-[#687386]">
          <span>Generated by AI Data Analyst · Schema-Agnostic Engine</span>
          <span>Verified In-Memory Computation</span>
        </div>
      </div>
    </div>
  );
};
