import React from 'react';
import { Dataset, AnalysisResult } from '../types/dataset';
import {
  FileText,
  Download,
  Printer,
  X,
  ShieldCheck,
  AlertTriangle,
  Sparkles,
  TrendingUp,
  Table,
} from 'lucide-react';
import { formatNumber } from '../utils/dataEngine';

interface ReportModalProps {
  dataset: Dataset;
  analysisResults: AnalysisResult[];
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({
  dataset,
  analysisResults,
  onClose,
}) => {
  const { quality, anomalies, records, columns, inferredSchema } = dataset;
  const primaryMeasure = Object.keys(inferredSchema).find(
    (c) => inferredSchema[c].role === 'measure'
  );
  const primaryDim = Object.keys(inferredSchema).find(
    (c) => inferredSchema[c].role === 'dimension'
  );

  const handlePrint = () => {
    window.print();
  };

  const handleExportCSV = () => {
    if (!records || records.length === 0) return;
    const header = columns.join(',');
    const rows = records.map((r) =>
      columns.map((c) => JSON.stringify(r[c] ?? '')).join(',')
    );
    const csvContent = 'data:text/csv;charset=utf-8,' + [header, ...rows].join('\n');
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement('a');
    link.setAttribute('href', encodedUri);
    link.setAttribute('download', `${dataset.fileName.replace(/\.[^/.]+$/, '')}_analysis_export.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/85 backdrop-blur-md p-4 sm:p-6 overflow-y-auto">
      <div className="w-full max-w-4xl rounded-3xl bg-slate-950 border border-slate-800 shadow-2xl overflow-hidden flex flex-col my-auto max-h-[92vh]">
        {/* Modal Top Bar */}
        <div className="p-5 border-b border-slate-800/80 flex items-center justify-between bg-slate-900/60 sticky top-0 z-20">
          <div className="flex items-center gap-3">
            <span className="p-2 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/30">
              <FileText className="w-5 h-5" />
            </span>
            <div>
              <h3 className="text-base font-bold text-white">Executive BI Intelligence Report</h3>
              <p className="text-xs text-slate-400">
                Generated by DataMind AI · {new Date().toLocaleDateString()}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleExportCSV}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white text-xs font-semibold transition-colors border border-slate-700/60"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Export CSV</span>
            </button>
            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-slate-950 text-xs font-bold transition-colors shadow-lg shadow-cyan-500/20"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>
            <button
              onClick={onClose}
              className="p-1.5 rounded-xl text-slate-400 hover:text-white hover:bg-slate-800 transition-colors ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Report Document */}
        <div id="printable-report" className="p-8 space-y-8 overflow-y-auto text-slate-200">
          {/* Document Header */}
          <div className="border-b border-slate-800 pb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
            <div>
              <div className="text-[11px] font-mono text-cyan-400 uppercase tracking-widest font-semibold mb-1">
                DataMind Autonomous Analysis
              </div>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white">
                {dataset.name || dataset.fileName}
              </h1>
              <p className="text-xs text-slate-400 mt-1">
                Source File: {dataset.fileName} · Analyzed: {new Date().toLocaleTimeString()}
              </p>
            </div>

            <div className="text-left sm:text-right">
              <span className="text-xs font-mono text-slate-400 block">Dataset Health</span>
              <span className="text-xl font-bold font-mono text-emerald-400">
                {quality.score} / 100 Score
              </span>
            </div>
          </div>

          {/* 1. Dataset Overview */}
          <section className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400">
              1. Dataset Overview & Schema Profile
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
              <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-800">
                <span className="text-[11px] text-slate-400">Total Rows</span>
                <div className="text-lg font-bold font-mono text-white mt-0.5">
                  {records.length.toLocaleString()}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-800">
                <span className="text-[11px] text-slate-400">Total Columns</span>
                <div className="text-lg font-bold font-mono text-white mt-0.5">
                  {columns.length}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-800">
                <span className="text-[11px] text-slate-400">Missing Values</span>
                <div className="text-lg font-bold font-mono text-slate-200 mt-0.5">
                  {quality.missingValuesCount}
                </div>
              </div>
              <div className="p-3.5 rounded-xl bg-slate-900 border border-slate-800">
                <span className="text-[11px] text-slate-400">Potential Outliers</span>
                <div className="text-lg font-bold font-mono text-amber-400 mt-0.5">
                  {anomalies.length}
                </div>
              </div>
            </div>
          </section>

          {/* 2. Detected Semantic Schema */}
          <section className="space-y-3">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400">
              2. Semantic Schema Mapping (Zero-Hardcoding)
            </h2>
            <div className="overflow-x-auto rounded-xl border border-slate-800">
              <table className="w-full text-left text-xs">
                <thead className="bg-slate-900 text-slate-400 font-mono">
                  <tr>
                    <th className="px-4 py-2.5">Dataset Column</th>
                    <th className="px-4 py-2.5">Inferred Role</th>
                    <th className="px-4 py-2.5">Business Concept</th>
                    <th className="px-4 py-2.5">Confidence</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-800 bg-slate-950/60 font-mono text-xs">
                  {columns.map((col) => {
                    const inf = inferredSchema[col];
                    return (
                      <tr key={col}>
                        <td className="px-4 py-2 font-semibold text-slate-200">{col}</td>
                        <td className="px-4 py-2 text-cyan-400 uppercase">{inf?.role || 'dimension'}</td>
                        <td className="px-4 py-2 text-slate-300 font-sans">{inf?.businessConcept || col}</td>
                        <td className="px-4 py-2 text-slate-400 uppercase">{inf?.confidence || 'high'}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>

          {/* 3. Analysis Findings & Explanations */}
          {analysisResults.length > 0 && (
            <section className="space-y-4">
              <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400">
                3. Calculated Questions & Mathematical Explanations ({analysisResults.length})
              </h2>

              <div className="space-y-4">
                {analysisResults.map((res, i) => (
                  <div key={res.id} className="p-5 rounded-2xl bg-slate-900/80 border border-slate-800 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="text-xs font-bold text-white">
                        #{i + 1}. {res.question}
                      </span>
                      <span className="text-[10px] font-mono uppercase px-2 py-0.5 rounded bg-cyan-500/10 text-cyan-300">
                        {res.plan.intent}
                      </span>
                    </div>

                    <div className="text-xs text-slate-300 bg-slate-950/80 p-3 rounded-xl border border-slate-800/80">
                      <strong>Answer:</strong> {res.answerSummary}
                    </div>

                    <div>
                      <span className="text-[11px] font-semibold text-slate-400 block mb-1">
                        Calculation Methodology:
                      </span>
                      <ul className="space-y-1 text-xs text-slate-400 list-disc list-inside">
                        {res.calculationSteps.map((s, idx) => (
                          <li key={idx}>{s}</li>
                        ))}
                      </ul>
                    </div>

                    {res.technicalFormula && (
                      <pre className="text-[11px] font-mono bg-slate-950 p-2.5 rounded-lg border border-slate-800 text-cyan-300 overflow-x-auto">
                        {res.technicalFormula}
                      </pre>
                    )}
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* 4. Anomalies Summary */}
          {anomalies.length > 0 && (
            <section className="space-y-3">
              <h2 className="text-sm font-bold uppercase tracking-wider text-slate-400">
                4. Statistical Outliers Detected ({anomalies.length})
              </h2>
              <div className="space-y-2">
                {anomalies.map((a) => (
                  <div
                    key={a.id}
                    className="p-3.5 rounded-xl bg-amber-950/15 border border-amber-900/30 text-xs flex items-center justify-between"
                  >
                    <div>
                      <span className="font-semibold text-amber-200">
                        Row #{a.rowNumber} ({a.columnName}): {formatNumber(Number(a.value))}
                      </span>
                      <p className="text-slate-400 text-[11px] mt-0.5">{a.reason}</p>
                    </div>
                    <span className="text-[10px] font-mono text-amber-400 uppercase font-bold shrink-0">
                      z = {a.zScore}
                    </span>
                  </div>
                ))}
              </div>
            </section>
          )}

          {/* Signoff */}
          <div className="pt-6 border-t border-slate-800 text-center text-xs text-slate-500 font-mono">
            Report autonomously compiled by DataMind AI Business Intelligence Engine · All calculations verified on source records.
          </div>
        </div>
      </div>
    </div>
  );
};
